index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::indexPage' }
index2:
    path: /index
    defaults: { _controller: 'App\Controller\IndexController::indexPage' }
adminDashboard:
    path: /admin/dashboard
    defaults: { _controller: 'App\Controller\AdminController::dashboard' }
login:
    path: /login
    defaults: { _controller: 'App\Controller\AuthController::login' }
