index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::indexPage' }
adminDashboard:
    path: /admin/dashboard
    defaults: { _controller: 'App\Controller\AdminController::dashboard' }
