<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxrednb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxrednb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxrednb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxrednb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVxrednb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vxrednb',
    'container.build_id' => '974a1723',
    'container.build_time' => 1519394930,
));
