<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJznunxk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJznunxk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJznunxk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJznunxk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJznunxk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Jznunxk',
    'container.build_id' => '86449990',
    'container.build_time' => 1519567994,
));
